logs for TcpServer, GateWay, internalException. delete qDebug.
Students-of-the-city-of-Kostroma/trpo_automation pull request #275
Opened 2020-06-12 15:36 UTC by AlbertShabrov

#259

2020-06-12 18:20 UTC, Someone-dono submitted a review, later dismissed

2020-06-13 09:00 UTC, None-stopCoding requested changes
Давай info все-таки один на класс, иначе потом будет воды много в логах, переводи в debug

2020-06-13 09:00 UTC, None-stopCoding commented on LR/07/src/components/strategylab.cpp
> +    log.logInfo("Check children");
статика же)

2020-06-19 16:37 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-19 17:44 UTC, Someone-dono approved these changes

2020-06-20 06:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-21 06:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-21 06:02 UTC, YuriSilenok commented
Добрый день. В ветке issue-275 давно не было активности

2020-06-22 06:01 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-23 06:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-24 06:01 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-25 06:01 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-25 13:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-25 13:05 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-26 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-26 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:02 UTC, YuriSilenok commented
Добрый день. В ветке issue-275 давно не было активности

2020-06-28 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-30 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 09:27 UTC, closed without merging